### ISSUE TITLE
How to build wenyan from source after it's change to typescript?

### ISSUE THREAD

**Issue by Fros1er** [wenyan-lang/wenyan#556] opened 2020-01-17 14:18 UTC
I tried 
```
npm i
npm run build
npm t (with several tests failed)
tsc .\src\cli.ts
```
, and 12 errors were found.

**Comment by antfu** [comment] 2020-01-17 14:49
Oh, I see. Are you using Windows? There seems like a bug changing timezone for calendar testing. I will fix them later. You may just ignore them for now. 😅

**Comment by Fros1er** [comment] 2020-01-17 14:52
> Oh, I see. Are you using Windows? There seems like a bug changing timezone for calendar testing. I will fix them later. You may just ignore them for now. 😅

The real problem is I can't compile it.

```
PS F:\code\wenyan\wenyan> tsc .\src\cli.ts
src/cli.ts:1:8 - error TS1192: Module '"fs"' has no default export.

1 import fs from "fs";
         ~~

src/cli.ts:2:8 - error TS1259: Module '"path"' can only be default-imported using the 'esModuleInterop' flag

2 import path from "path";
         ~~~~

  node_modules/@types/node/path.d.ts:152:5
    152     export = path;
            ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

src/cli.ts:3:8 - error TS1259: Module '"F:/code/wenyan/wenyan/node_modules/commander/typings/index"' can only be default-imported using the 'esModuleInterop' flag

3 import commander from "commander";
         ~~~~~~~~~

  node_modules/commander/typings/index.d.ts:302:1
    302 export = commander;
        ~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

src/cli.ts:4:8 - error TS1259: Module '"F:/code/wenyan/wenyan/node_modules/find-up/index"' can only be default-imported using the 'esModuleInterop' flag

4 import findUp from "find-up";
         ~~~~~~

  node_modules/find-up/index.d.ts:137:1
    137 export = findUp;
        ~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

src/converts/hanzi2pinyin.ts:2:20 - error TS2732: Cannot find module './hanzi2roman-map-pinyin.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

2 import pinyin from "./hanzi2roman-map-pinyin.json";
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/converts/hanzi2pinyin.ts:3:20 - error TS2732: Cannot find module './hanzi2roman-map-baxter.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

3 import baxter from "./hanzi2roman-map-baxter.json";
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/converts/hanzi2pinyin.ts:7:17 - error TS2494: Using a string in a 'for...of' statement is only supported in ECMAScript 5 and higher.

7   for (var c of s) {
                  ~

src/converts/hanzi2pinyin.ts:22:19 - error TS2494: Using a string in a 'for...of' statement is only supported in ECMAScript 5 and higher.

22   for (const x of a) {
                     ~

src/keywords.ts:120:13 - error TS2339: Property 'fromEntries' does not exist on type 'ObjectConstructor'.

120 if (!Object.fromEntries) {
                ~~~~~~~~~~~

src/keywords.ts:121:10 - error TS2339: Property 'fromEntries' does not exist on type 'ObjectConstructor'.

121   Object.fromEntries = l => {
             ~~~~~~~~~~~

src/keywords.ts:128:32 - error TS2339: Property 'fromEntries' does not exist on type 'ObjectConstructor'.

128 export const KEYWORDS = Object.fromEntries(ke);
                                   ~~~~~~~~~~~

src/version.ts:1:25 - error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

1 export { version } from "../package.json";
                          ~~~~~~~~~~~~~~~~~


Found 12 errors.
```

**Comment by antfu** [comment] 2020-01-17 15:02
Fixed in a183295a297a67ee77f224f24e61439df46f5b8e. I also added a shortcut for that `npm run cli`. Please try it out. Thanks!

**Comment by Fros1er** [comment] 2020-01-17 15:26
`npm run cli` failed.
```
PS F:\code\wenyan\wenyan> npm run cli

> wenyanlang@0.3.0 cli F:\code\wenyan\wenyan
> ts-node ./src/cli.ts


F:\code\wenyan\wenyan\node_modules\ts-node\src\index.ts:533
          throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`)
                ^
TypeError: src\version.js: Emit skipped
    at getOutput (F:\code\wenyan\wenyan\node_modules\ts-node\src\index.ts:533:17)
    at Object.compile (F:\code\wenyan\wenyan\node_modules\ts-node\src\index.ts:735:32)
    at Module.m._compile (F:\code\wenyan\wenyan\node_modules\ts-node\src\index.ts:814:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (F:\code\wenyan\wenyan\node_modules\ts-node\src\index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wenyanlang@0.3.0 cli: `ts-node ./src/cli.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wenyanlang@0.3.0 cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Froster\AppData\Roaming\npm-cache\_logs\2020-01-17T15_18_48_624Z-debug.log
```

debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'cli' ]
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose run-script [ 'precli', 'cli', 'postcli' ]
5 info lifecycle wenyanlang@0.3.0~precli: wenyanlang@0.3.0
6 info lifecycle wenyanlang@0.3.0~cli: wenyanlang@0.3.0
7 verbose lifecycle wenyanlang@0.3.0~cli: unsafe-perm in lifecycle true
8 verbose lifecycle wenyanlang@0.3.0~cli: PATH: [hidden]
9 verbose lifecycle wenyanlang@0.3.0~cli: CWD: F:\code\wenyan\wenyan
10 silly lifecycle wenyanlang@0.3.0~cli: Args: [ '/d /s /c', 'ts-node ./src/cli.ts' ]
11 silly lifecycle wenyanlang@0.3.0~cli: Returned: code: 1  signal: null
12 info lifecycle wenyanlang@0.3.0~cli: Failed to exec cli script
13 verbose stack Error: wenyanlang@0.3.0 cli: `ts-node ./src/cli.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid wenyanlang@0.3.0
15 verbose cwd F:\code\wenyan\wenyan
16 verbose Windows_NT 10.0.17763
17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "cli"
18 verbose node v10.14.2
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error wenyanlang@0.3.0 cli: `ts-node ./src/cli.ts`
22 error Exit status 1
23 error Failed at the wenyanlang@0.3.0 cli script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And `npm run dev` stuck here:

```
PS F:\code\wenyan\wenyan> npm run dev

> wenyanlang@0.3.0 dev F:\code\wenyan\wenyan
> npm run clear && npm run build:type && webpack --mode development --watch


> wenyanlang@0.3.0 clear F:\code\wenyan\wenyan
> rimraf dist typings


> wenyanlang@0.3.0 build:type F:\code\wenyan\wenyan
> tsc --emitDeclarationOnly --declaration --declarationDir ./typings && move-cli ./typings/package.d.ts ./typings/package.json.d.ts


webpack is watching the files…

(node:4344) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:4344) DeprecationWarning: Compilation.moduleTemplate: Use Compilation.moduleTemplates.javascript instead
(node:4344) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
Hash: 4f3935dc8ed35e271b15b988509bf4704422534c544eda22556bd6696e33
Version: webpack 4.41.4
Child
    Hash: 4f3935dc8ed35e271b15
    Time: 8068ms
    Built at: 2020-01-17 23:21:54
                   Asset      Size  Chunks                   Chunk Names
        cli/index.min.js  1.17 MiB     cli  [emitted]        cli
    cli/index.min.js.map   505 KiB     cli  [emitted] [dev]  cli
    Entrypoint cli = cli/index.min.js cli/index.min.js.map
    [./package.json] 3.1 KiB {cli} [built]
    [./src/cli.ts] 13.1 KiB {cli} [built]
    [./src/converts/hanzi2num.ts] 30.3 KiB {cli} [built]
    [./src/converts/hanzi2pinyin.ts] 1.36 KiB {cli} [built]
    [./src/execute.ts] 1.95 KiB {cli} [built]
    [./src/highlight.js] 4.74 KiB {cli} [built]
    [./src/keywords.ts] 3.42 KiB {cli} [built]
    [./src/macro.ts] 6.75 KiB {cli} [built]
    [./src/parser.ts] 27.6 KiB {cli} [built]
    [./src/reader.ts] 4.9 KiB {cli} [built]
    [./src/render.ts] 13 KiB {cli} [built]
    [./src/version.ts] 157 bytes {cli} [built]
    [fs] external "fs" 42 bytes {cli} [built]
    [path] external "path" 42 bytes {cli} [built]
    [readline] external "readline" 42 bytes {cli} [built]
        + 33 hidden modules
Child
    Hash: b988509bf4704422534c
    Time: 7338ms
    Built at: 2020-01-17 23:21:53
                    Asset     Size  Chunks                   Chunk Names
        core/index.min.js  1.1 MiB    core  [emitted]        core
    core/index.min.js.map  406 KiB    core  [emitted] [dev]  core
    Entrypoint core = core/index.min.js core/index.min.js.map
    [./lib sync recursive .*\.wy$] ./lib sync .*\.wy$ 324 bytes {core} [optional] [built]
    [./package.json] 3.1 KiB {core} [built]
    [./src/converts/hanzi2num.ts] 30.3 KiB {core} [built]
    [./src/converts/hanzi2pinyin.ts] 1.36 KiB {core} [built]
    [./src/converts/hanzi2roman-map-baxter.json] 143 KiB {core} [built]
    [./src/execute.ts] 1.95 KiB {core} [built]
    [./src/keywords.ts] 3.42 KiB {core} [built]
    [./src/macro.ts] 6.75 KiB {core} [built]
    [./src/parser.ts] 27.6 KiB {core} [built]
    [./src/reader.ts] 4.9 KiB {core} [built]
    [./src/stdlib.ts] 805 bytes {core} [built]
    [./src/transpilers/index.ts] 469 bytes {core} [built]
    [./src/typecheck.ts] 22.4 KiB {core} [built]
    [./src/utils.ts] 350 bytes {core} [built]
    [./src/version.ts] 157 bytes {core} [built]
        + 18 hidden modules
Child
    Hash: 544eda22556bd6696e33
    Time: 7562ms
    Built at: 2020-01-17 23:21:54
                       Asset      Size   Chunks                   Chunk Names
         render/index.min.js  1.12 MiB   render  [emitted]        render
     render/index.min.js.map   434 KiB   render  [emitted] [dev]  render
        runtime/index.min.js   1.1 MiB  runtime  [emitted]        runtime
    runtime/index.min.js.map   409 KiB  runtime  [emitted] [dev]  runtime
    Entrypoint render = render/index.min.js render/index.min.js.map
    Entrypoint runtime = runtime/index.min.js runtime/index.min.js.map
    [./src/browser_runtime.ts] 5.61 KiB {runtime} [built]
    [./src/converts/hanzi2num.ts] 30.3 KiB {render} {runtime} [built]
    [./src/converts/hanzi2pinyin.ts] 1.36 KiB {render} {runtime} [built]
    [./src/execute.ts] 1.95 KiB {render} {runtime} [built]
    [./src/highlight.js] 4.74 KiB {render} [built]
    [./src/keywords.ts] 3.42 KiB {render} {runtime} [built]
    [./src/macro.ts] 6.75 KiB {render} {runtime} [built]
    [./src/parser.ts] 27.6 KiB {render} {runtime} [built]
    [./src/reader.ts] 4.9 KiB {render} {runtime} [built]
    [./src/render.ts] 13 KiB {render} [built]
    [./src/stdlib.ts] 805 bytes {render} {runtime} [built]
    [./src/transpilers/index.ts] 469 bytes {render} {runtime} [built]
    [./src/typecheck.ts] 22.4 KiB {render} {runtime} [built]
    [./src/utils.ts] 350 bytes {render} {runtime} [built]
    [./src/version.ts] 157 bytes {render} {runtime} [built]
        + 21 hidden modules
```

**Comment by antfu** [comment] 2020-01-17 15:41
> npm run cli failed.

I could not reproduce that. Can you run `npm ci` and try it again?

> And npm run dev stuck here:

This is expected behavior and it's not `stuck`. It will keep watching file changes and rebuild automatically. You can find the dist files under `dist` folder

**Comment by Fros1er** [comment] 2020-01-18 01:33
Even npm ci had an error...

```
(python2) F:\code\wenyan\wenyan>npm ci
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.11 install F:\code\wenyan\wenyan\node_modules\fsevents
> node-gyp rebuild


(python2) F:\code\wenyan\wenyan\node_modules\fsevents>if not defined npm_config_node_gyp (node "E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Traceback (most recent call last):
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\code\wenyan\wenyan\node_modules\fsevents
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> nodemon@2.0.2 postinstall F:\code\wenyan\wenyan\node_modules\nodemon
> node bin/postinstall || exit 0


> husky@3.1.0 install F:\code\wenyan\wenyan\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@3.1.0 postinstall F:\code\wenyan\wenyan\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

added 1164 packages in 100.101s
```

And `npm run cli` failed again, same as it's previous time.

By the way, 
```
npm -v
6.4.1

node -v
v10.14.2

tsc -v
Version 3.7.5
```

**Closed** 2021-12-27 09:45 UTC
Labels: contributor-tools
