### ISSUE TITLE
Feature request: Ri Jing (Date package)

### ISSUE THREAD

**Issue by kaiyuan01** [wenyan-lang/wenyan#455] opened 2019-12-31 15:54 UTC
This package will return the Chinese calendar date (Yin Li or Nong Li) given a Gregorian date. It will also return if it's a holiday and the name of the holiday, or the date of significance such as 24 Jie2 Qi4.

It will have a suite of nice render functions to print nice calendars with Chinese holidays annotated, which are configurable.

This can be a very useful package, very timely as the New Year is going to start and Chinese New Year is also well around the corner - wenyan-lang will definitely be remembered even just for this package alone!

Who is up to this challenge? (May I suggest this be given higher priority in our to-do list?)

**Comment by LingDong-** [comment] 2019-12-31 16:19
Hi @kaiyuan01 thanks for bringing this up, though I think it is a duplicate of #425. Since there's already an extended conversation in that issue, I propose we take our discussion there.

P.S. Printing a calendar with annotated holiday sounds like good example for the `./examples` folder to showcase the datetime library, not as part of the datetime library :)

**Closed** 2020-02-02 18:07 UTC
Labels: stdlib
